package Appointment;

import dao.MedicalExaminationDAO;
import dao.ProfessionalDAO;
import dao.ServiceDAO;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import model.Customer;
import model.MedicalExamination;
import model.Professional;
import model.Service;

/**
 *
 * @author ADMIN
 */
public class Appointment extends HttpServlet {

    private ServiceDAO serviceDAO = new ServiceDAO();
    private ProfessionalDAO professionalDAO = new ProfessionalDAO();
    private MedicalExaminationDAO medicalExaminationDAO = new MedicalExaminationDAO();

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        List<Service> services = serviceDAO.getAllService();
        List<Professional> doctors = professionalDAO.getAllDoctors();

        request.setAttribute("services", services);
        request.setAttribute("doctors", doctors);

        request.getRequestDispatcher("appointment.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession session = request.getSession();
        Customer customerProfile = (Customer) session.getAttribute("customerAccount");

        if (customerProfile == null) {
            response.sendRedirect("login.jsp");
            return;
        }

        // Retrieve form data
        String[] serviceIds = request.getParameterValues("serviceIds[]"); // Array of selected service IDs
        String doctorId = request.getParameter("doctorId");
        String dateStr = request.getParameter("date"); // Expected format: dd/MM/yyyy (e.g., 13/03/2025)
        String timeStr = request.getParameter("time"); // Expected format: HH:mm (e.g., 14:30)
        String name = request.getParameter("name");
        String phone = request.getParameter("phone");
        String message = request.getParameter("message");

        // Define formatter for parsing the date and time
        DateTimeFormatter inputFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        // Combine date and time and parse it
        String examinationDateTimeStr = dateStr + " " + timeStr; // e.g., "13/03/2025 14:30"
        LocalDateTime examinationDateTime = LocalDateTime.parse(examinationDateTimeStr, inputFormatter);
        String examinationDate = examinationDateTime.format(outputFormatter); // Convert to "yyyy-MM-dd HH:mm:ss"

        // Get current timestamp for createdAt
        String createdAt = LocalDateTime.now().format(outputFormatter);

        // Fetch Professional object based on doctorId
        Professional doctor = professionalDAO.getProfessionalbyID(Integer.parseInt(doctorId));

        // Fetch selected services
        List<Service> selectedServices = new ArrayList<>();
        if (serviceIds != null) {
            for (String serviceId : serviceIds) {
                Service service = serviceDAO.getServiceById(Integer.parseInt(serviceId));
                if (service != null) {
                    selectedServices.add(service);
                }
            }
        }

        // Create MedicalExamination object
        MedicalExamination examination = new MedicalExamination();
        examination.setExaminationID(0); // Assuming ID is auto-generated by the database
        examination.setExaminationDate(examinationDate); // Set the formatted date
        examination.setCustomerId(customerProfile);
        examination.setStatus("Pending"); // Default status
        examination.setConsultantId(doctor);
        examination.setNote(message);
        examination.setCreatedAt(createdAt);
        examination.setList(selectedServices);

        // Save to database using DAO
        boolean success = medicalExaminationDAO.saveMedicalExamination(examination);

        if (success) {
            // Redirect to a success page or show a success message
            response.sendRedirect("confirmation.jsp");
        } else {
            // Handle failure (e.g., show error message)
            request.setAttribute("error", "Failed to book appointment. Please try again.");
            request.getRequestDispatcher("appointment.jsp").forward(request, response);
        }
    }

    @Override
    public String getServletInfo() {
        return "Handles appointment booking for medical examinations";
    }
}